<?php

namespace app\models;

use Yii;
use cornernote\linkall\LinkAllBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property resource $user_image
 * @property string $created_at
 * @property string $updated_at
 * @property integer $status
 *
 * @property SkillSet[] $skillSets
 * @property EducationDetail[] $educationDetails
 * @property ExperienceDetail[] $experienceDetails
 * @property Project[] $projects
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public $skill_ids;
    public $imageFile;
    public $education_detail;

    public function rules()
    {
        return [
            [['username', 'auth_key', 'password_hash', 'email'], 'required'],
            [['user_image'], 'string'],
            [['skill_ids'], 'required'],
            [['imageFile'], 'file'],
            [['created_at', 'updated_at'], 'safe'],
            [['education_detail'], 'safe'],
            [['status'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'skill_ids' => 'My Talent',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'imageFile' => 'User Image',
            'user_image' => 'User Image',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
        ];
    }

    public function behaviors()
    {
        //return parent::behaviors(); // TODO: Change the autogenerated stub
        return [
            LinkAllBehavior::className(),
        ];
    }



    public function afterSave($insert, $changedAttributes)
    {
        $skills = [];
        foreach ($this->skill_ids as $skill_name) {
            $skill = Skill::getSkillByName($skill_name);
            if ($skill) {
                $skills[] = $skill;
            }
        }
        $this->linkAll('skills', $skills);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProjects()
    {
        return $this->hasMany(Project::className(), ['user_id' => 'id']);
    }
    public function getSkills(){
        return $this->hasMany(Skill::className(), ['id' => 'skill_id'])
            ->viaTable('skill_set', ['user_id' => 'id']);

    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSkillSets()
    {
        return $this->hasMany(SkillSet::className(), ['user_id' => 'id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEducationDetails()
    {
        return $this->hasMany(EducationDetail::className(), ['user_id' => 'id']);

    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExperienceDetails()
    {
        return $this->hasMany(ExperienceDetail::className(), ['user_id' => 'id']);
    }
}
